# helm/mp-umbrella/charts/external-secrets/templates/secret-store.yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.secretStore.name }}
  labels:
    platform.mp/version: "v6.0"
spec:
  provider:
    vault:
      server: {{ .Values.secretStore.vault.server }}
      path: {{ .Values.secretStore.vault.path }}
      auth:
        kubernetes:
          mountPath: {{ .Values.secretStore.vault.mountPath }}
          role: {{ .Values.secretStore.vault.role }}
          serviceAccountRef:
            name: external-secrets-vault-auth
      version: v2